---
abstract: 'Catalyst style console debugging for plack apps'
author:
  - 'Matthew Phillips <mattp@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-DebugLogging
requires:
  HTTP::Message: 0
  Plack: 0
  Term::Size::Any: 0
  Text::SimpleTable: 0
resources:
  repository: git://github.com/mattp-/Plack-Middleware-DebugLogging.git
version: 0.001001
