---
abstract: 'Catalyst style console debugging for plack apps'
author:
  - 'Matthew Phillips <mattp@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-DebugLogging
requires:
  Data::Dumper::Concise: 0
  Data::Serializer::Raw: 0
  HTTP::Message: 0
  Module::Runtime: 0
  Plack: 0
  Term::Size::Any: 0
  Text::SimpleTable: 0
  Try::Tiny: 0
resources:
  bugtracker: https://github.com/mattp-/Plack-Middleware-DebugLogging/issues
  homepage: https://github.com/mattp-/Plack-Middleware-DebugLogging
  repository: https://github.com/mattp-/Plack-Middleware-DebugLogging.git
version: 0.001004
